name: cmake

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  cmake:
    name: cmake
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [self-hosted-ubuntu-22.04, self-hosted-ubuntu-20.04, self-hosted-rhel-8, self-hosted-ubuntu-22.04-arm64, self-hosted-windows-2022]
        BUILD_TYPE: [Release, Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DVSP_TESTS=ON -DVSP_CLI=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} -j $(nproc)

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure
