name: cmake

on:
  push:
    branches:
      - 'main'
      - 'dev**'

env:
  GITHUB_TOKEN: ${{secrets.CI_TOKEN}}

jobs:
  cmake:
    name: cmake
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2022]
        BUILD_TYPE: [Release, Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y build-essential clang-tidy ninja-build

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DVSP_TESTS=ON -DVSP_CLI=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}} -j $(nproc)

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.BUILD_TYPE}} --output-on-failure
